# Generated by CMake, DO NOT EDIT

empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/janverrept/Documents/Development/Projects/Personal/Xcode/MacSunnySender/Frameworks/YASDI/build-xcode/CMakeFiles/3.10.0/CMakeCCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/janverrept/Documents/Development/Projects/Personal/Xcode/MacSunnySender/Frameworks/YASDI/build-xcode/CMakeFiles/3.10.0/CMakeSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/janverrept/Documents/Development/Projects/Personal/Xcode/MacSunnySender/Frameworks/YASDI/yasdi-1/projects/generic-cmake/../../include/version.h.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/janverrept/Documents/Development/Projects/Personal/Xcode/MacSunnySender/Frameworks/YASDI/yasdi-1/projects/generic-cmake/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/janverrept/Documents/Development/Projects/Personal/Xcode/MacSunnySender/Frameworks/YASDI/yasdi-1/projects/generic-cmake/incprj/project.h.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/CMakeCInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/CMakeCommonLanguageInclude.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/CMakeGenericSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/CMakeLanguageInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/CMakeSystemSpecificInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/Compiler/AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/Compiler/CMakeCommonCompilerMacros.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/Compiler/Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/Compiler/GNU.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/Platform/Darwin-AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/Platform/Darwin-Clang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/Platform/Darwin-Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/Platform/Darwin-Initialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/Platform/Darwin.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/Platform/UnixPaths.cmake))

/Users/janverrept/Documents/Development/Projects/Personal/Xcode/MacSunnySender/Frameworks/YASDI/build-xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.10.0/bin/cmake -H/Users/janverrept/Documents/Development/Projects/Personal/Xcode/MacSunnySender/Frameworks/YASDI/yasdi-1/projects/generic-cmake -B/Users/janverrept/Documents/Development/Projects/Personal/Xcode/MacSunnySender/Frameworks/YASDI/build-xcode
